# Generated by Django 3.1 on 2020-09-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
